spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

  datasource:
    url: "jdbc:mysql://ali.117503445.top:3399/dbbookmanager?serverTimezone=GMT&useUnicode=true&characterEncoding=utf-8"
    username: root
    password: hbhb

server:
  servlet:
    encoding:
      charset: utf-8